{{- $values := $.Values.reth }}
{{- $jwtEnabled := or $values.jwt.existingSecret.name $values.jwt.fromLiteral }}
{{- $jwtSecretName := default (print (include "reth.fullname" .) "-reth-jwt") $values.jwt.existingSecret.name }}
{{- if and $jwtEnabled (not $values.jwt.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $jwtSecretName }}
  labels:
    {{- include "reth.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.hex: {{ $values.jwt.fromLiteral | b64enc }}
{{- end }}
